module.exports  = {
    COUNTER_ADD : 'COUNTER_ADD',
    COUNTER_REMOVE : 'COUNTER_REMOVE',
    UPDATE_COUNTER : 'UPDATE_COUNTER',

    GET_USERS:'GET_USERS',

    AUTH:'AUTH',
    LOGOUT:'LOGOUT',


    IS_OPENED_USER_MODAL:'IS_OPENED_USER_MODAL',

    VISIBLE_ROUTE_LINE: 'VISIBLE_ROUTE_LINE',

    ACTIVE_LOADER: 'ACTIVE_LOADER'
}